// <auto-generated />
namespace MvcMovieCST238.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddDirectorIDMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDirectorIDMig));
        
        string IMigrationMetadata.Id
        {
            get { return "201305032132477_AddDirectorIDMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
